name: "Benchmark Aphrodite Eval"
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: rexielscarlet
    - run: nix-shell -p nixos-rebuild --run "make dry HOST=Aphrodite; make time HOST=Aphrodite"
