name: "Populate cachix cache"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'npins/**'
      - 'pkgs/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: rexielscarlet
        authToken: '${{ secrets.CACHIX_API_KEY }}'
    - run: make pkg PKG=anime-launchers.sleepy-launcher
    - run: make pkg PKG=lanzaboote.tool
    - run: make pkg PKG=kurukurubar-unstable
    - run: make pkg PKG=nixvim
    - run: make pkg PKG=mbake
